### ISSUE TITLE
Chrome on Android devices let me not input more than 1 number in mode NATURAL

### ISSUE THREAD

**Issue by Maverickcg** [nbfontana/ngx-currency#100] opened 2020-06-23 12:11 UTC
Hello

We use your directive in our project and we like it and did not experience problems until now. But yesterday we did a user test and the user had an Android device running chrome. He told us that he was not able to insert any currency values other than the ones with just one number. In Our case for example:

Input: `1` --> Output: `1,00 €`

All other inputs are not accepted. I investigated this issue and found a reason.

If running AndroidChrome the directive does not do `handleKeypress()` but instead `handleInput()`. This sets the cursor to the end of the input fields text after the first number input or before all subsequent inputs.
If the user has input the above number and now inputs 2 the resulting rawValue looks like `1,00 €2`. This gets converted to `1002` and then truncated to `100` in `inputService` and the final result is again `1,00 €`.
On all devices other than Android with Chrome the `handleInput()` method is not used and the cursors position is not set to the end what leads to the expected output. Is this the intended behaviour or did I miss something here?

Best regards

**Comment by PavelShell** [comment] 2020-07-08 08:06
I'm facing this issue too.

**Comment by PavelShell** [comment] 2020-07-09 12:31
Okay, i've fix it. PR will be soon.

**Comment by PavelShell** [comment] 2020-07-09 14:11
> Hello
> 
> We use your directive in our project and we like it and did not experience problems until now. But yesterday we did a user test and the user had an Android device running chrome. He told us that he was not able to insert any currency values other than the ones with just one number. In Our case for example:
> 
> Input: `1` --> Output: `1,00 €`
> 
> All other inputs are not accepted. I investigated this issue and found a reason.
> 
> If running AndroidChrome the directive does not do `handleKeypress()` but instead `handleInput()`. This sets the cursor to the end of the input fields text after the first number input or before all subsequent inputs.
> If the user has input the above number and now inputs 2 the resulting rawValue looks like `1,00 €2`. This gets converted to `1002` and then truncated to `100` in `inputService` and the final result is again `1,00 €`.
> On all devices other than Android with Chrome the `handleInput()` method is not used and the cursors position is not set to the end what leads to the expected output. Is this the intended behaviour or did I miss something here?
> 
> Best regards

 #103

**Comment by jlabanca** [comment] 2020-07-15 14:00
This is a duplicate of Issue #90

**Closed** 2020-08-05 18:30 UTC

**Comment by nbfontana** [comment] 2020-08-05 18:31
Fixed at ngx-currency@2.4.0
